version: "3.1"
services:
  dusite:
    image: jmzsoftware/du_download_site:latest
    container_name: dusite
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - <DIR_WITH_DEVICE_FOLDERS>:/var/www/html/devices
    environment:
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - SLACK_TOKEN=${SLACK_TOKEN}
