version: "3.1"
services:
  dusite:
    image: jmzsoftware/du_download_site:latest
    container_name: dusite
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - <DIR_WITH_DEVICE_FOLDERS>:/var/www/html/devices
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - SLACK_TOKEN=${SLACK_TOKEN}
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./downloads.sql:/docker-entrypoint-initdb.d/downloads.sql
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
